-- "취미로" Supabase 데이터베이스 테이블 정의 스키마 (schema.sql)

-- 1. 개인식별 및 기본 인증 정보 테이블 (민감 감정 정보와 격리)
CREATE TABLE IF NOT EXISTS user_auth (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 사용자 프로필 및 취미 DNA 상태 테이블 (감정, 번아웃 등 민감 정보 포함 - 1:1 관계)
CREATE TABLE IF NOT EXISTS user_profile (
    id UUID PRIMARY KEY REFERENCES user_auth(id) ON DELETE CASCADE,
    energy_level INTEGER DEFAULT 0,
    burnout_state VARCHAR(50),
    current_emotion VARCHAR(100),
    budget VARCHAR(50),
    sociality VARCHAR(50),
    activity VARCHAR(50),
    motive JSONB,
    outcome_style VARCHAR(50),
    space_sensory JSONB,
    novelty_preference VARCHAR(50),
    session_duration VARCHAR(50),
    riasec_inferred JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. 취미 마스터 테이블 (데이터셋과 매핑)
CREATE TABLE IF NOT EXISTS hobby_profile (
    hobby_id VARCHAR(50) PRIMARY KEY,
    hobby_name VARCHAR(255) NOT NULL, -- 취미명
    riasec_code VARCHAR(10) NOT NULL,
    initial_cost VARCHAR(50),         -- 초기비용
    ongoing_cost VARCHAR(50),         -- 지속비용
    session_time VARCHAR(50),         -- 세션당시간
    space_type VARCHAR(100),          -- 공간
    social_type VARCHAR(100),         -- 사회성
    intensity_level VARCHAR(50),      -- 강도
    learning_curve VARCHAR(100),      -- 학습곡선
    achievement_type VARCHAR(100),    -- 성취방식
    sensory_tags VARCHAR(255),        -- 감각태그
    novelty_level VARCHAR(50),        -- 신규성
    beginner_action TEXT,             -- beginner_action(첫행동)
    materials TEXT,                   -- 준비물
    safety_notes TEXT,                -- safety_notes(안전)
    external_path TEXT,               -- 외부시작경로
    rag_description TEXT,             -- RAG설명(임베딩본문)
    rag_keywords TEXT,                -- RAG검색키워드
    is_synthetic BOOLEAN DEFAULT FALSE,
    cost_verification VARCHAR(50),    -- 비용검증상태
    safety_verification VARCHAR(50),  -- 안전검증상태
    fallback_set BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. 피드백 및 추천 이력 테이블 (피드백 점수 및 텍스트)
CREATE TABLE IF NOT EXISTS feedback_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES user_auth(id) ON DELETE CASCADE,
    recommendations JSONB NOT NULL,
    feedback_score INTEGER,
    feedback_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. 비즈니스 및 사용자 활동 로그 테이블
CREATE TABLE IF NOT EXISTS business_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES user_auth(id) ON DELETE SET NULL,
    event_type VARCHAR(100) NOT NULL,
    event_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 인덱스 설정
CREATE INDEX IF NOT EXISTS idx_user_profile_updated ON user_profile(updated_at);
CREATE INDEX IF NOT EXISTS idx_hobby_riasec ON hobby_profile(riasec_code);
CREATE INDEX IF NOT EXISTS idx_feedback_user ON feedback_history(user_id);
CREATE INDEX IF NOT EXISTS idx_business_event_type ON business_event(event_type);
